import { Permission } from './permissions';

export type RoleKey = 'owner' | 'manager' | 'cashier' | 'waiter' | 'kitchen' | 'readonly';

export interface BuiltInRoleDefinition {
  key: RoleKey;
  name: string;
  description: string;
  permissions: Permission[];
  isSystem: true;
}

export const BUILT_IN_ROLES: BuiltInRoleDefinition[] = [
  {
    key: 'owner',
    name: 'Owner',
    description: 'Full access to everything — only one Owner per restaurant.',
    permissions: ['*'],
    isSystem: true,
  },
  {
    key: 'manager',
    name: 'Manager',
    description: 'Day-to-day operations: menu, staff, orders, billing, reports.',
    permissions: [
      'restaurant:read',
      'restaurant:update',
      'user:read',
      'user:create',
      'user:update',
      'role:read',
      'menu:read',
      'menu:create',
      'menu:update',
      'menu:delete',
      'menu:publish',
      'menu:86',
      'menu:import',
      'menu:export',
      'table:read',
      'table:create',
      'table:update',
      'table:delete',
      'qr:read',
      'qr:create',
      'qr:update',
      'qr:delete',
      'order:read',
      'order:create',
      'order:accept',
      'order:modify',
      'order:void',
      'order:cancel',
      'order:refund',
      'kds:read',
      'kds:update',
      'billing:read',
      'billing:create',
      'billing:discount',
      'billing:settle',
      'payment:read',
      'payment:create',
      'payment:refund',
      'inventory:read',
      'inventory:create',
      'inventory:update',
      'inventory:delete',
      'inventory:stockin',
      'inventory:stockout',
      'customer:read',
      'customer:update',
      'feedback:read',
      'feedback:reply',
      'discount:read',
      'discount:create',
      'discount:update',
      'discount:delete',
      'discount:apply',
      'coupon:read',
      'coupon:create',
      'coupon:update',
      'coupon:delete',
      'loyalty:read',
      'loyalty:config',
      'loyalty:redeem',
      'notification:read',
      'notification:template',
      'notification:send',
      'report:read',
      'report:export',
      'audit:read',
      'day:close',
    ],
    isSystem: true,
  },
  {
    key: 'cashier',
    name: 'Cashier',
    description: 'Billing and payments at the counter.',
    permissions: [
      'restaurant:read',
      'menu:read',
      'table:read',
      'order:read',
      'billing:read',
      'billing:create',
      'billing:settle',
      'payment:read',
      'payment:create',
      'customer:read',
      'customer:update',
      'discount:apply',
      'coupon:read',
      'loyalty:read',
      'loyalty:redeem',
      'report:read',
    ],
    isSystem: true,
  },
  {
    key: 'waiter',
    name: 'Waiter / Captain',
    description: 'Takes assisted orders, manages tables, serves food.',
    permissions: [
      'restaurant:read',
      'menu:read',
      'table:read',
      'table:update',
      'order:read',
      'order:create',
      'order:accept',
      'kds:read',
      'customer:read',
      'feedback:read',
    ],
    isSystem: true,
  },
  {
    key: 'kitchen',
    name: 'Kitchen Staff',
    description: 'Operates the KDS — accepts and prepares orders.',
    permissions: ['restaurant:read', 'menu:read', 'order:read', 'kds:read', 'kds:update', 'menu:86'],
    isSystem: true,
  },
  {
    key: 'readonly',
    name: 'Read Only',
    description: 'View-only access. Useful for auditors or trainees.',
    permissions: [
      'restaurant:read',
      'menu:read',
      'table:read',
      'qr:read',
      'order:read',
      'kds:read',
      'billing:read',
      'payment:read',
      'inventory:read',
      'customer:read',
      'feedback:read',
      'discount:read',
      'coupon:read',
      'loyalty:read',
      'notification:read',
      'report:read',
    ],
    isSystem: true,
  },
];
